language: ruby
rvm:
    - 2.6.3
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache:
  bundler: true
  directories:
  - $TRAVIS_BUILD_DIR/node_modules

#before_install:
#    - nvm install 9.5.0
#    - nvm use 9.5.0

branches:
  only:
  - master

install:
  - gem install jekyll html-proofer
script:
  - jekyll build
#  - htmlproofer ./_site

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: _site
  repo: HackCancer/hackcancer.github.io
  target_branch: master
  on:
    branch: master

notifications:
    email: false
